remote_theme: dleidert/jekyll-wgdd

title: "[erfahrungen, meinungen, halluzinationen]"
description: "ein kleines, privates Blog"
excerpt: >
  A private site with contents about myself, my daily Debian usage and
  contributions, my hobbies like aquaristics, photography, mushrooms,
  environmental protection and general thoughts about daily life.
lang: en

show_excerpts: false

author: Daniel Leidert
email: webmaster@wgdd.de

google_analytics: false
google_site_verification: false

permalink: /:year/:month/:title #pretty
highlighter: rouge
markdown: kramdown

jekyll_wgdd:
  site_conf:
    skin: 'default'
    debug: true
    expires: false
    mobile:
      theme_color: "#CC0033"

collections:
  legals:
  debian:
    title: 'My Debian'
    output: true
    permalink: /debian/:path
  authors:
    output: true
    permalink: /about/:name/

plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
