theme: jekyll-wgdd

title: Site title
author: GitHub User
email: user@github.com
description: >
  Site description

show_excerpts: false

google_analytics: false
google_site_verification: false

jekyll_wgdd:
  site_conf:
    skin: 'default'
    debug: false
    expires: false
    mobile:
      theme_color: "#CC0033"

include:
- .htaccess
- _pages

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
