remote_theme: dleidert/jekyll-wgdd

title: "[erfahrungen, meinungen, halluzinationen]"
description: "ein kleines, privates blog"
lang: en

show_excerpts: false

author: Daniel Leidert
email: daniel.leidert@wgdd.de

google_analytics: false
google_site_verification: false

permalink: pretty
highlighter: rouge
markdown: kramdown

jekyll_wgdd:
  site_conf:
    skin: 'default'
    debug: true
    expires: false
    mobile:
      theme_color: "#CC0033"

collections:
  legals:
  authors:
    output: true
    permalink: /about/:name/

plugins:
- jekyll-feed
- jekyll-paginate
#- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
